export default {
    REQUEST_MOVIES_LIST: 'REQUEST_MOVIES_LIST',
    SUCCESS_MOVIES_LIST: 'SUCCESS_MOVIES_LIST',
    ERROR_MOVIES_LIST: 'ERROR_MOVIES_LIST',
    REQUEST_MOVIE_DETAILS: 'REQUEST_MOVIE_DETAILS',
    SUCCESS_MOVIE_DETAILS: 'SUCCESS_MOVIE_DETAILS',
    ERROR_MOVIE_DETAILS: 'ERROR_MOVIE_DETAILS',
    REQUEST_MOVIES_SEARCH: 'REQUEST_MOVIES_SEARCH',
    SUCCESS_MOVIES_SEARCH: 'SUCCESS_MOVIES_SEARCH',
    ERROR_MOVIES_SEARCH: 'ERROR_MOVIES_SEARCH',
    CLEAR_MOVIES_SEARCH: 'CLEAR_MOVIES_SEARCH',
}